# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 19:03
from __future__ import unicode_literals

import apps.obras.models
from django.conf import settings
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=450)),
                ('direccion', models.TextField()),
                ('imagen', sorl.thumbnail.fields.ImageField(blank=True, upload_to=apps.obras.models.path_and_rename)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(editable=False)),
                ('fecha_modificacion', models.DateTimeField(editable=False)),
                ('administrador', models.ManyToManyField(blank=True, related_name='administradores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
