# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obras.Estado'),
            preserve_default=False,
        ),
    ]
