# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 22:09
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_obra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='imagen',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='obra',
            name='imagen',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=None),
        ),
    ]
