# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0004_auto_20160826_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='obra',
            name='fecha_termino',
            field=models.DateField(),
        ),
    ]
