# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 22:03
from __future__ import unicode_literals

import apps.obras.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0005_auto_20160826_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='imagen',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=apps.obras.models.PathAndRename(b'estados')),
        ),
        migrations.AlterField(
            model_name='obra',
            name='imagen',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=apps.obras.models.PathAndRename(b'obras')),
        ),
    ]
