# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='colonia_fisica',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cp_fisico',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='curp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='delegacion_fisica',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='direccion_fisica',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pass_user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='poblacion_fisica',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rfc',
        ),
    ]
