# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20160818_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id_inquilino',
        ),
    ]
