# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 18:46
from __future__ import unicode_literals

import apps.ac22.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificaciones',
            name='anexo',
            field=models.FileField(upload_to=None, validators=[apps.ac22.validators.validate_file_extension_pdf]),
        ),
    ]
