# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especificaciones', '0003_auto_20160829_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especificaciones',
            old_name='nombre',
            new_name='nombre_documento',
        ),
    ]
