# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especificaciones', '0004_auto_20160829_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificaciones',
            name='nombre_anexo',
            field=models.CharField(default='anexo', max_length=450),
            preserve_default=False,
        ),
    ]
