# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especificaciones', '0006_historicalespecificaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalespecificaciones',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalespecificaciones',
            name='parent',
        ),
        migrations.DeleteModel(
            name='HistoricalEspecificaciones',
        ),
    ]
