# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 21:47
from __future__ import unicode_literals

import apps.ac22.validators
import apps.especificaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especificaciones', '0007_auto_20160829_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificaciones',
            name='tipo_propuesta',
            field=models.CharField(choices=[(b'propuesta_economica', b'Propuesta economica'), (b'propuesta_tecnica', 'Propuesta tecnica')], default=b'propuesta_economica', max_length=450),
        ),
        migrations.AlterField(
            model_name='especificaciones',
            name='anexo',
            field=models.FileField(upload_to=apps.especificaciones.models.PathAndRename(b'/especificaciones'), validators=[apps.ac22.validators.validate_file_extension_pdf]),
        ),
        migrations.AlterField(
            model_name='especificaciones',
            name='nombre_documento',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
