# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_financiera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='concepto',
            field=models.CharField(default=1, max_length=450),
            preserve_default=False,
        ),
    ]
