# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_financiera', '0002_ingreso_concepto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
