# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_financiera', '0003_auto_20160909_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_financiera.Cuenta'),
            preserve_default=False,
        ),
    ]
