# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_financiera', '0006_gasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=450)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_financiera.Gasto')),
            ],
        ),
    ]
