# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 17:26
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_de_conceptos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concepto',
            name='parent',
        ),
        migrations.AlterField(
            model_name='agrupador',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogo_de_conceptos.Agrupador', verbose_name=b'Padre'),
        ),
    ]
