# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_de_conceptos', '0002_auto_20160908_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agrupador',
            old_name='concepto',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='concepto',
            name='agrupador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogo_de_conceptos.Agrupador'),
            preserve_default=False,
        ),
    ]
