# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_de_conceptos', '0003_auto_20160908_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concepto',
            name='level',
        ),
        migrations.RemoveField(
            model_name='concepto',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='concepto',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='concepto',
            name='tree_id',
        ),
    ]
