# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_de_conceptos', '0004_auto_20160908_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrupador',
            name='descripcion',
            field=models.TextField(max_length=450),
        ),
        migrations.AlterField(
            model_name='concepto',
            name='concepto',
            field=models.TextField(max_length=450),
        ),
    ]
